[project]
name = "cssr"
version = "0.0.1a1"
description = "Compressive Sensing-based Super-Resolution Framework"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    {name = "Marcelo Looser", email = "marcelo.looser@outlook.com"}
]
keywords = [
    "compressed-sensing", 
    "sparse-recovery", 
    "super-resolution", 
    "signal-processing", 
    "low-pass filtering",
    "thermal broadening",
    "instrumental broadening",
    "STM"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Physics",
]

dependencies = [
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "matplotlib>=3.3.0",
    "cvxpy>=1.5.0"
]

[project.optional-dependencies]
test = [
    "pytest"
]

[project.urls]
"Homepage" = "https://github.com/marcelolooser/cssr"
"Issues" = "https://github.com/marcelolooser/cssr/issues"